export default {
  '{delete}': 'entf',
  '{insert}': 'enfg',
  '{home}': 'pos1',
  '{end}': 'ende',
  '{pageUp}': 'BILD↑',
  '{pageDown}': 'BILD↓',
  '{f1}': 'f1',
  '{f2}': 'f2',
  '{f3}': 'f3',
  '{f4}': 'f4',
  '{f5}': 'f5',
  '{f6}': 'f6',
  '{f7}': 'f7',
  '{f8}': 'f8',
  '{f9}': 'f9',
  '{f10}': 'f10',
  '{f11}': 'f11',
  '{f12}': 'f12',
  '{spc}': 'ä?.',
  '{numbers}': '123',
  '{enter}': '↩',
  '{escape}': 'esc ⎋',
  '{tab}': '⇥',
  '{backspace}': '⌫',
  '{capslock}': 'caps lock ⇪',
  '{shift}': '⇧',
  '{controlleft}': 'ctrl ⌃',
  '{controlright}': 'ctrl ⌃',
  '{altleft}': 'alt ⌥',
  '{altright}': 'alt ⌥',
  '{metaleft}': 'cmd ⌘',
  '{metaright}': 'cmd ⌘',
  '{default}': 'abc',
  '{fn}': 'fn',
}
